apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: hds
  name: hds-nfs
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.60
    path: "/volume1/hds"
