apiVersion: batch/v1
kind: CronJob
metadata:
  name: hds-trawler
  namespace: hds
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hds-report-activity
            image: rdomloge/hds-container:v1.2
            imagePullPolicy: IfNotPresent
            command:
            - python3
            - hds.py
            volumeMounts:
            - name: storage
              mountPath: /hds-latest/activity
          restartPolicy: OnFailure
          volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: pvc
